spring.application.name=master-crawler
server.port=8081

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/mastercrawler
spring.datasource.username=root
spring.datasource.password=

spring.thymeleaf.prefix=classpath:/templates/
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bing=trace
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.springframework.http.client=DEBUG
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB



server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.ai.openai.chat.options.model=gemini-2.0-flash
gemini.api.url=https://api.avalai.ir/v1
gemini.api.key=aa-aLU74PbC5jcFkzTVYmBhGWPTvKWtfDxHOR2ZlbR7e2WiP0dR
gemini.pro.key=aa-TZUGuEXLxhAG0XzLbwpCpqKtBRM2tXO7JuOlfqS9a3g2jPbF
whisper.api.key=aa-gMxRQ04IUcbHN9U8UimvnQRtromL8rMpKuc3J26IwefX3f33

#Selenium configuration
selenium.chrome.headless=true
selenium.chrome.timeout=30
selenium.chrome.implicit-wait=10
selenium.chrome.page-load-timeout=30

# Social Media Publishing Configuration
app.encryption.key=Kj8#mN2$pQ7*vW9@xC5^yF3&zB6!tE4%rU1+sA8-dG0)hL9~
# X (Twitter) API Configuration
# Updated credentials for new X app
x.api.key=PZEMPuQaqNVZThaYLo66FLCpx
x.api.secret=D6nm28uL0C6O2eWBpEQmIeMDLFksgDX4hP8JxyRwuVUrAujwn4
x.bearer.token=AAAAAAAAAAAAAAAAAAAAAOEO4QEAAAAAurR1A9B3PDi%2Fll4qb4LHs%2B0JDWk%3DYBkhZuZWCg7vHq9V1yG48GwCFFxOLbKIY9D4bl8URjES8lgqVd
x.oauth.client-id=QmwyQWhLdmZvZHRwOWZ5MHBxX0s6MTpjaQ
x.oauth.client-secret=O71R3cZjseTYW5SAQak-gfyuHKDWoN4JNzlLcpHW-qbYg2nJ7H
x.oauth.redirect-uri=http://localhost:8081/socials/x/callback